CREATE TABLE `esp32_sample_data` (
  `ESP_ID` int(11) NOT NULL AUTO_INCREMENT,
  `ESP_SERIAL_NO` varchar(64) NOT NULL,
  `ESP_MAC_ADDRESS` varchar(64) NOT NULL,
  `ESP_DATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `ESP_HUMIDITY` int(11) DEFAULT NULL,
  `ESP_TEMPERATURE` int(11) DEFAULT NULL,
  `ESP_UPDATED_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ESP_ID`)
) ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=latin1 COMMENT='Sample Data (Humidity and Temprature) from ESP32';


MySql Login:
------------
sudo mysql -u root -h localhost esp32SampleData -p


Samples:
--------
CREATE TABLE `users` (
  `userid` int(11) NOT NULL AUTO_INCREMENT,
  `email` varchar(80) NOT NULL,
  `username` varchar(64) NOT NULL,
  `password` char(32) NOT NULL,
  `displayname` varchar(64) DEFAULT NULL,
  PRIMARY KEY (`userid`),
  UNIQUE KEY `email` (`email`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;

CREATE TABLE `hrm_nameplate` (
  `HRM_ID` int(11) NOT NULL AUTO_INCREMENT,
  `HRM_SerialNo` varchar(64) NOT NULL,
  `HRM_LOCATION` varchar(64) NOT NULL,
  `HRM_FW_VERSION` varchar(64) NOT NULL,
  `HRM_DATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `HRM_IP_ET0` varchar(32) NOT NULL,
  `HRM_IP_ET1` varchar(32) NOT NULL,
  `HRM_IP_PPP` varchar(32) NOT NULL,
  `HRM_IP_HMI` varchar(32) NOT NULL,
  `HRM_HMI_COMM_STATUS` varchar(32) NOT NULL,
  `HRM_UPDATED_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`HRM_ID`)
) ENGINE=MyISAM AUTO_INCREMENT=10 DEFAULT CHARSET=latin1 COMMENT='Nameplate of HRMs';

CREATE TABLE `hmiban00001` (
  `HMI_ID` int(11) NOT NULL AUTO_INCREMENT,
  `HMI_PARAMETERS` varchar(128) DEFAULT NULL,
  `HMI_VALUES` float DEFAULT NULL,
  PRIMARY KEY (`HMI_ID`)
) ENGINE=MyISAM AUTO_INCREMENT=5 DEFAULT CHARSET=latin1 COMMENT='HMIs Params and Values';
